### ISSUE TITLE
Error Code 7

### ISSUE THREAD

**Issue by Alppuccino** [Zac-McDonald/iCUE-Custom-Game-Integration#1]
Hi, I'm getting error code 7 when trying to set the keyboard to a specific profile. AFAIK, error 7 is when there is no priorities file, however, I do have a priorities file.
![image](https://user-images.githubusercontent.com/30245509/68391749-29eb5c00-0160-11ea-85d3-398e86fb30b9.png)

the image attached above is my "EchoArena" folder in "GameSdkEffects" folder. 

![image](https://user-images.githubusercontent.com/30245509/68391798-4ab3b180-0160-11ea-836c-757ae6a52ae4.png)
the image above is my "priorities.cfg" file.

Do you have any idea why this is happening?
TIA.

**Comment by Zac-McDonald** [comment]
So as far as I can tell, you've got it all set up correctly. With the error codes, besides the ones that exist in the public SDK, they aren't documented, so I have no way to actually know what a code of 7 is. When I was testing the program, not having a priorities file consistently threw that error so I assumed that was the problem, but your setup looks correct so I'm not sure. 

If you haven't already, I recommend you try all the functions (SetGame, SetState, ClearState, SetEvent) within the [documentation ](https://zac-mcdonald.github.io/iCUE-Custom-Game-Integration/) to test if the setup is correct. Sorry I can't really help beyond that, as I said, it all looks setup correctly.

If you could post the console output of the server that would definitely help me to follow what's going on.
