### ISSUE TITLE
HTTP POST should be used for all actions with change the state

### ISSUE THREAD

**Issue by Legion2** [Zac-McDonald/iCUE-Custom-Game-Integration#3]
Always use POST if the request intends to change state or triggers an action. GET should only be used for getting data without changing the state. POST request can have a body, which can contain for example json data. Currently the HTTP API is not really a REST API, it does not consider the url path, HTTP Method, request body, parameter encoding as part of the api. It's currently only a RPC like api over HTTP.

**Comment by Zac-McDonald** [comment]
It's not supposed to be a REST API, dude. The idea is that almost everything universally supports HTTP GET requests, as well as there being a lot less complexity to using them. There are a few use cases, for example desktop shortcuts, that would require significantly more effort to work with POST requests, which ultimately goes against my main goal of a blanket solution applicable to almost any use case.

**Comment by Legion2** [comment]
Oh sorry, somehow I thought it supposed to be a REST API. But thanks anyway for your great work @Zac-McDonald.

I will try to create a CLI to simply set profiles form the command line using this HTTP server.

**Comment by Legion2** [comment]
@Zac-McDonald I created a cli client that uses the HTTP server to change iCUE profiles and list all games and profiles https://github.com/Legion2/open-cue-cli
